In [4]:
from collections import deque

def bfs(graph, start):
    visited = set()  # Set to keep track of visited nodes
    queue = deque([start])  # Initialize the queue with the starting node
    visited.add(start)  # Mark the starting node as visited

    while queue:
        current_node = queue.popleft()  # Dequeue the front node
        print(current_node, end=" ")  # Print the value of the current node

        # Explore neighbors of the current node
        for neighbor in graph[current_node]:
            if neighbor not in visited:
                visited.add(neighbor)
                queue.append(neighbor)

# Example usage:
if __name__ == "__main__":
    # Create an adjacency list (graph)
    graph = {
        0: [1, 3],
        1: [2, 4],
        2: [5],
        3: [1, 2],
        4: [],
        5: []
    }

    print("Breadth First Traversal:")
    bfs(graph, 0)


Breadth First Traversal:
0 1 3 2 4 5 

In [1]:
from collections import deque

class Graph:
    def __init__(self, graph_dict=None):
        if graph_dict is None:
            graph_dict = {}
        self.graph_dict = graph_dict

    def bfs(self, start):
        visited = set()
        queue = deque([start])
        visited.add(start)

        while queue:
            current_node = queue.popleft()
            print(current_node, end=" ")  # Print the value of the current node

            for neighbor in self.graph_dict[current_node]:
                if neighbor not in visited:
                    visited.add(neighbor)
                    queue.append(neighbor)

# Example usage:
if __name__ == "__main__":
    graph_elements = {
        "A": ["B", "S"],
        "B": ["A", "D", "C"],
        "C": ["B", "E"],
        "D": ["B"],
        "E": ["C", "F", "H"],
        "F": ["E", "G"],
        "G": ["F"],
        "H": ["E"],
        "S": ["A", "G"]
    }

    g = Graph(graph_elements)
    print("Depth First Algorithm:")
    g.bfs("A")


Depth First Algorithm:
A B S D C G E F H 

In [11]:
import numpy as np

# Heuristic function using Manhattan distance
def heuristic(state):
    goal_state = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 0]])
    return np.sum(np.abs(state - goal_state))

# A* algorithm for 8-puzzle problem
def a_star(initial_state):
    frontier = [(heuristic(initial_state), 0, initial_state, [])]
    explored = set()

    while frontier:
        _, cost, state, path = min(frontier)
        frontier.remove((_, cost, state, path))

        if np.array_equal(state, goal_state):
            return path + [state]

        explored.add(tuple(state.reshape(-1)))

        for neighbor, move in gen_neighbors(state):
            if tuple(neighbor.reshape(-1)) in explored:
                continue

            neighbor_cost = cost + 1
            frontier.append((heuristic(neighbor) + neighbor_cost,
                             neighbor_cost,
                             neighbor,
                             path + [move]))

    return []

# Generate neighbors and corresponding moves for a given state
def gen_neighbors(state):
    zero_index = np.where(state == 0)
    zero_row, zero_col = zero_index[0][0], zero_index[1][0]

    neighbors = [np.zeros_like(state)] * 4
    moves = [(0, -1), (-1, 0), (0, 1), (1, 0)]

    for i, (row_offset, col_offset) in enumerate(moves):
        new_row, new_col = zero_row + row_offset, zero_col + col_offset
        if 0 <= new_row < 3 and 0 <= new_col < 3:
            neighbors[i][zero_row, zero_col] = state[new_row, new_col]
            neighbors[i][new_row, new_col] = 0
            yield neighbors[i], f'move {i+1}'

# Initialize the puzzle
goal_state = np.array([[1, 2, 3], [8, 0, 4], [7, 6, 5]])
initial_state = np.array([[1, 8, 7], [4, 2, 3], [6, 5, 0]])

# Find the solution using A* algorithm
solution = a_star(initial_state)

# Print the solution
print('INITIAL STATE')
print(initial_state)
print('\nFINAL STATE')
print(goal_state)
print('\nSOLUTION:')
for i, state in enumerate(solution):
    print(f'Step {i+1}:')
    print(state)

INITIAL STATE
[[1 8 7]
 [4 2 3]
 [6 5 0]]

FINAL STATE
[[1 2 3]
 [8 0 4]
 [7 6 5]]

SOLUTION:
